### ISSUE TITLE
dolitle cli fails creation of central dolittle folder on Mac

### ISSUE THREAD

**Issue by xstof** [dolittle-obsolete/cli#42]
Repro on Mac:
- `npm install -g @dolittle/cli`
- `dolittle`

Fails with

```sh
info: Central Dolittle folder does not exist - creating it and setting up default configuration
fs.js:137
    throw new ERR_INVALID_CALLBACK();
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at makeCallback (fs.js:137:11)
    at Object.mkdir (fs.js:713:16)
    at ConfigManager.makeSureCentralFolderExists (/usr/local/lib/node_modules/@dolittle/cli/bin/configuration/ConfigManager.js:63:20)
    at new ConfigManager (/usr/local/lib/node_modules/@dolittle/cli/bin/configuration/ConfigManager.js:91:37)
    at new global (/usr/local/lib/node_modules/@dolittle/cli/bin/global.js:88:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/@dolittle/cli/bin/global.js:278:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
```

**Comment by woksin** [comment]
I have seen this error before, not on my own macbook, but on other people's Windows machines. In those cases it seems like there was a problem when creating a folder with a name starting with a ".".

I'm on it

**Comment by woksin** [comment]
@xstof if you could try updating to the new cli now (npm update/install -g @dolittle/cli) and also deleting the  .dolittle folder in root if you have that. I published a hotfix that should fix this

**Comment by xstof** [comment]
Fixed.  Awesome; thanks!
